const express = require('express');
const router = express.Router();
const { checkApiLimit } = require('../middleware/authMiddleware');
const apiCtrl = require('../controllers/apiController');

router.get('/hydromind', checkApiLimit, apiCtrl.aiHydromindController);
router.get('/gemini-image', checkApiLimit, apiCtrl.geminiImageController);
router.get('/luminai', checkApiLimit, apiCtrl.aiLuminaiController);
router.get('/bibli', checkApiLimit, apiCtrl.bibliController);
router.get('/deepseek', checkApiLimit, apiCtrl.deepseekController);
router.get('/douyin', checkApiLimit, apiCtrl.douyinController);
router.get('/genshinstalk', checkApiLimit, apiCtrl.genshinStalkController);
router.get('/gemini', checkApiLimit, apiCtrl.geminiController);
router.get('/heroml', checkApiLimit, apiCtrl.heroMlController);
router.get('/gpt4-1', checkApiLimit, apiCtrl.gpt41Controller);
router.get('/googlesearch', checkApiLimit, apiCtrl.googleSearchController);
router.get('/gpt4-o', checkApiLimit, apiCtrl.gpt4oController);
router.get('/toanime', checkApiLimit, apiCtrl.toAnimeController);
router.get('/igstalk', checkApiLimit, apiCtrl.igStalkController);
router.get('/mediafire', checkApiLimit, apiCtrl.mediafireController);
router.get('/instagram', checkApiLimit, apiCtrl.instagramController);
router.get('/enhance', checkApiLimit, apiCtrl.enhanceController);
router.get('/upscale', checkApiLimit, apiCtrl.upscaleController);
router.get('/restore', checkApiLimit, apiCtrl.restoreController);
router.get('/colorize', checkApiLimit, apiCtrl.colorizeController);
router.get('/removebg', checkApiLimit, apiCtrl.removebgController);
router.get('/genius', checkApiLimit, apiCtrl.lirikController);
router.get('/llama', checkApiLimit, apiCtrl.metaController);
router.get('/pinterest', checkApiLimit, apiCtrl.pinterestController);
router.get('/spotify', checkApiLimit, apiCtrl.spotifyController);
router.get('/twitter', checkApiLimit, apiCtrl.twitterController);
router.get('/tozombie', checkApiLimit, apiCtrl.toZombieController);
router.get('/ytmp4', checkApiLimit, apiCtrl.ytmp4Controller);
router.get('/text2img', checkApiLimit, apiCtrl.text2imgController);
router.get('/ytmp3', checkApiLimit, apiCtrl.ytmp3Controller);
router.get('/whisper', checkApiLimit, apiCtrl.whisperController);
router.get('/tiktok', checkApiLimit, apiCtrl.tiktokController);

module.exports = router;